dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libboost-all-dev
install:
  - pushd ~
  # Install cmake 3.9.4
  - wget https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz
  - tar zxvf cmake-3.9.4-Linux-x86_64.tar.gz
  - pushd cmake-3.9.4-Linux-x86_64
  - sudo cp -r ./* /usr/
  - popd
  # Install gtest
  - git clone https://github.com/google/googletest.git
  - pushd googletest
  - mkdir -p build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - sudo make install
  - popd
  - popd
  # Done
  - popd
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest